<?php


namespace Magenest\Test\Model;
use Magento\Framework\Model\AbstractModel;

class Address extends AbstractModel
{
    public function _construct()
    {
        $this->_init('Magenest\Test\Model\ResourceModel\Address');
//        parent::_construct(); // TODO: Change the autogenerated stub
    }
}