<?php


namespace Magenest\Staff\Model;
use Magento\Framework\Model\AbstractModel;

class Staff extends AbstractModel
{
    public function _construct()
    {
        $this->_init('Magenest\Staff\Model\ResourceModel\Staff');
//        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
