<?php


namespace Magenest\Test\Model\ResourceModel\Address;
use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;

class Collection extends AbstractCollection
{
    public function _construct()
    {
        $this->_init('Magenest\Test\Model\Address', 'Magenest\Test\Model\ResourceModel\Address');
//        parent::_construct(); // TODO: Change the autogenerated stub
    }
}