<?php


namespace Magenest\WeddingEvent\Model;
use Magento\Framework\Model\AbstractModel;

class WeddingEvent extends AbstractModel
{
    public function _construct()
    {
        $this->_init('Magenest\WeddingEvent\Model\ResourceModel\WeddingEvent');
//        parent::_construct(); // TODO: Change the autogenerated stub
    }
}
